---
title: "IDC6700 Project"
author: "Rakesh Kumar Surapani"
date: "4/26/2022"
output: html_document
---

```{r}
library(ggplot2)
library(readr)
library(dplyr)
library(lubridate)
library(zoo)
library(reshape2)
library(plotly)


```

```{r}

hotel_bookings <- read_csv("hotel_bookings.csv")
View(hotel_bookings)


```

```{r}

summary(hotel_bookings)

```
```{r}

count_df = as.data.frame(table(hotel_bookings$is_canceled))
head(count_df)

ggplot(count_df, aes(x= c("Non-canceled", "canceled"), y = Freq))+
  geom_bar(stat="identity", position=position_dodge(width=0.8), width = 0.7, fill = "lightblue")+
  geom_text(aes(label = Freq), vjust = 1.5)+
  xlab("")+
  ylab("Count")+
  ggtitle("Total count of canceled and non canceled hotel bookings")+
  theme(text=element_text(size=14, family="Times"))
          

```


```{r}
count_df = as.data.frame(table(hotel_bookings$is_canceled, hotel_bookings$hotel))

count_df$Var1 = as.character(count_df$Var1)

count_df[count_df == "0"] = "Non-canceled"
count_df[count_df == "1"] = "canceled"
head(count_df)

colnames(count_df)[2] = "Hotel_type" 

ggplot(count_df, aes(x= Var1, y = Freq, fill = Hotel_type))+
  geom_bar(stat="identity", position= "dodge", width = 0.7)+
 # geom_text(aes(label = Freq), vjust = 1.5, hjust = 3)+
  xlab("Reservation")+
  ylab("Count")+
  ggtitle("Total count of canceled and non canceled hotel bookings")+
  theme(text=element_text(size=14, family="Times"))
```

```{r}
non_cancelled_res = subset(hotel_bookings, hotel_bookings$is_canceled == 0)

non_cancelled_res$guests = non_cancelled_res$adults+non_cancelled_res$children + non_cancelled_res$babies

mapdf = data.frame(
  non_cancelled_res$arrival_date_month, non_cancelled_res$hotel, non_cancelled_res$arrival_date_year, non_cancelled_res$guests
) 
colnames(mapdf) = c("arrival_date_month", "hotel", "arrival_date_year", "guests")

mapdf = subset(mapdf, mapdf$guests != 0)
#View(mapdf)

heatmapdf = mapdf %>%
  group_by(arrival_date_month, arrival_date_year, hotel) %>%
  summarise(people = sum(as.numeric(guests)))
head(heatmapdf)

```

HEAT MAP FOR the GUEST BOOKINGS OVER TIME.
```{r}

ggplot(heatmapdf, aes(x = factor(arrival_date_month, levels=c("January", "February", "March","April", "May", "June", "July", "August", "September", "October", "November", "December")), y =  factor(arrival_date_year, levels = c(2017,2016,2015)), fill = people))+
  geom_tile()+
  scale_fill_distiller(palette = "Magma", direction=1)+
  geom_text(aes(label = people), size = 3)+
  #scale_x_discrete(limits = c("Jan", "Feb", "Mar","Apr", "May", "Jun", "Sep", "Oct", "Nov", "Dec"))+
  facet_grid(hotel ~ .)+
  xlab("Month")+
  ylab("Year")+
  ggtitle("Heatmap of guests")+
  theme(text=element_text(size=14, family="Times"),axis.text.x = element_text(angle = 30, hjust = 1))


```
ROOM COST VARIATION IN HOTELS. 

```{r}

Roomdf = data.frame(
  non_cancelled_res$arrival_date_month, non_cancelled_res$hotel, non_cancelled_res$adr, non_cancelled_res$guests
) 
colnames(Roomdf) = c("arrival_date_month", "Hotel", "adr", "guests")

Roomdf = subset(Roomdf, Roomdf$adr > 0)


#View(Roomdf)
df = Roomdf %>%
  group_by(Hotel, arrival_date_month) %>%
  summarise(price = sum(as.numeric(adr))/sum(as.numeric(guests)))
head(df)

```

```{r}

ggplot(df, aes(x = factor(arrival_date_month, levels=c("January", "February", "March","April", "May", "June", "July", "August", "September", "October", "November", "December")), y =  price, fill = Hotel))+
  geom_bar(stat="identity", position= "dodge", width = 0.7)+
  #geom_text(aes(label = price), vjust = 1.5, hjust = 3)+
  xlab("Month")+
  ylab("Price Per Guest")+
  ggtitle("Room cost per guest based on month and hotel")+
  theme(text=element_text(size=14, family="Times"),axis.text.x = element_text(angle = 30, hjust = 1))

```

Room Cancellations

```{r}

RoomCandf = as.data.frame(table(hotel_bookings$is_canceled, hotel_bookings$hotel, hotel_bookings$arrival_date_month))
RoomCandf = subset(RoomCandf, RoomCandf$Var1 == 1)

colnames(RoomCandf)[1:3] = c("is_canceled","Hotel","arrival_date_month")
#View(RoomCandf)

ggplot(RoomCandf, aes(x = factor(arrival_date_month, levels=c("January", "February", "March","April", "May", "June", "July", "August", "September", "October", "November", "December")), y =  Freq, fill = Hotel))+
  geom_bar(stat="identity", position= "dodge", width = 0.7)+
  #geom_text(aes(label = price), vjust = 1.5, hjust = 3)+
  xlab("Month")+
  ylab("Canceled count")+
  ggtitle("Canceletion count based on month and hotel type")+
  theme(text=element_text(size=14, family="Times"),axis.text.x = element_text(angle = 30, hjust = 1))

```


Tree Diagram

```{r}
library(treemap)
library(treemapify)

Roomcostdf = data.frame(
  non_cancelled_res$hotel, non_cancelled_res$adr, non_cancelled_res$guests, non_cancelled_res$reserved_room_type
) 
colnames(Roomcostdf) = c("Hotel", "adr", "guests", "reserved_room_type")

Roomcostdf = subset(Roomcostdf, Roomdf$adr > 0)


#View(Roomdf)
df = Roomcostdf %>%
  group_by(Hotel, reserved_room_type) %>%
  summarise(price_of_reserved_room_type = sum(as.numeric(adr))/sum(as.numeric(guests)))


df1 = subset(df, df$Hotel == "City Hotel")

fig1 <- plot_ly(
  type="treemap",
  labels=df1$reserved_room_type,
  parents = c("City Hotel","City Hotel","City Hotel","City Hotel","City Hotel","City Hotel","City Hotel"),
  values = df1$price_of_reserved_room_type,
  marker=list(colorscale='Reds'),
   textinfo="label+value")


fig1



df2 = subset(df, df$Hotel != "City Hotel")

fig2 <- plot_ly(
  type="treemap",
  labels=df2$reserved_room_type,
  parents = c("Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel","Resort Hotel"),
  values = df2$price_of_reserved_room_type,
  marker=list(colorscale='Reds'),
   textinfo="label+value")


fig2
```



Meal Price per guest

```{r}
library(tidyverse)
library(hrbrthemes)
library(viridis)

Mealdf = data.frame(
  non_cancelled_res$meal, non_cancelled_res$hotel, non_cancelled_res$adr, non_cancelled_res$guests
) 
colnames(Mealdf) = c("meal", "Hotel", "adr", "guests")

Mealdf = subset(Mealdf, Mealdf$adr > 0)

boxdf = Mealdf

#View(Mealdf)
df = Mealdf %>%
  group_by(Hotel, meal) %>%
  summarise(price = sum(as.numeric(adr))/sum(as.numeric(guests)))

df = subset(df, df$meal !="Undefined")
#View(df)

ggplot(df, aes(x = meal, y =  price, fill = Hotel))+
  geom_bar(stat="identity", position= "dodge", width = 0.7)+
  xlab("Meal Type")+
  ylab("Price Per Person")+
  ggtitle("Meal Type cost per person")+
  theme(text=element_text(size=14, family="Times"),axis.text.x = element_text(angle = 30, hjust = 1))


boxdf = subset(boxdf, boxdf$meal !="Undefined")
boxdf$price = boxdf$adr/boxdf$guests

boxplot(price ~meal*Hotel,data=boxdf,col=(c("gold","darkgreen")), main="Meal Type cost per person",
   xlab="Meal Type", ylab="Price Per Person")


ggplot(boxdf, aes(x = meal, y =  price, fill = Hotel))+
  geom_violin() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6, option="A") +
  xlab("Meal Type")+
  ylab("Price Per Person")+
  ggtitle("Meal Type cost per person")+
  theme(text=element_text(size=14, family="Times"))
  

```